###
GET  http://localhost:80/getAll

###
GET http://localhost:80/getAssets/1

###
POST http://localhost:80/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="avatar.png"
Content-Type: image/jpeg

< ./public/avatar.jpeg
--boundary--

###
POST http://localhost:80/delete
Content-Type: application/json

{
  "id": "648d68fac7fad4ff8f9e1488"
}

###
POST http://localhost:80/deleteAll
Content-Type: application/json

{}